# Generated by Django 4.1.7 on 2023-03-20 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aws_access_key_id', models.CharField(max_length=100)),
                ('aws_secret_access_key', models.CharField(max_length=200)),
                ('output_path', models.CharField(max_length=200)),
                ('local_path', models.CharField(max_length=200)),
                ('bucket_name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('input_field_path', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=30)),
                ('is_enable', models.BooleanField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMTPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('admin_email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('server', models.CharField(max_length=100)),
                ('bcc', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=30)),
                ('is_enable', models.BooleanField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'SMTP Settings',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='draft', max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('report_day', models.IntegerField()),
                ('am_email', models.CharField(max_length=500)),
                ('download_link', models.CharField(max_length=500)),
                ('schedule_date', models.DateTimeField(blank=True, null=True)),
                ('run_date', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.client')),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.reporttype')),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=500)),
                ('report_day', models.IntegerField()),
                ('am_email', models.CharField(max_length=500)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.client')),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.reporttype')),
            ],
        ),
    ]
